import { test, expect } from '@playwright/test';
import * as path from 'path';
import { pathToFileURL } from 'url';
import { visualFixtures } from '../../src/__tests__/fixtures/visual';

/**
 * Lane B — pixel regression over the visual fixture corpus (issue #252).
 *
 * Loads the generated gallery (the real `ScoreEditor` SVG output), waits for the Bravura
 * music font to finish loading, and screenshots each fixture's stage, diffing against the
 * committed (CI/linux) baseline. The gallery is (re)generated by global-setup before this
 * runs, so screenshots always reflect current source.
 *
 * The fixture list is imported from the SAME source Lane A uses — one corpus, two lanes.
 */

const galleryUrl = pathToFileURL(
  path.resolve(__dirname, '../../visual-gallery/index.html')
).href;

test.describe('visual pixel regression (#252)', () => {
  for (const fixture of visualFixtures) {
    test(fixture.name, async ({ page }) => {
      await page.goto(galleryUrl);
      // Ensure the SMuFL font is actually rasterized before capturing (the key Lane-B
      // determinism guard — a screenshot before font load would diff against tofu glyphs).
      await page.evaluate(() => document.fonts.ready);
      const stage = page.locator(`#${fixture.name} .stage`);
      await expect(stage).toHaveScreenshot(`${fixture.name}.png`);
    });
  }
});
