/**
 * Visual gallery generator — Lane B's cheap "see it" step (issue #252).
 *
 * Renders every fixture to inline SVG and writes a single static HTML page so a human can
 * open one file and visually scan the whole corpus. This is the immediate, dependency-free
 * form of visual verification — it does not diff anything; it just lets you LOOK. The
 * automated pixel-diff (full Lane B) is the Playwright suite.
 *
 * Run on demand (it is SKIPPED in the normal test run):
 *   npm run visual:gallery     # writes ./visual-gallery/index.html, then open it
 *
 * The Bravura (SMuFL) font is copied next to the HTML and @font-face'd so the glyphs
 * actually render when you open the file.
 */

jest.mock('@/engines/toneEngine', () => ({
  playNote: jest.fn(),
  setInstrument: jest.fn(),
  isSamplerLoaded: jest.fn(() => false),
  InstrumentType: {},
}));

import * as fs from 'fs';
import * as path from 'path';
import { visualFixtures } from '../fixtures/visual';
import { renderScore } from '../helpers/visual';

const ENABLED = process.env.VISUAL_GALLERY === '1';
const OUT_DIR = path.resolve(__dirname, '../../../visual-gallery');
const FONT_SRC = path.resolve(__dirname, '../../assets/fonts/Bravura.woff2');

const escapeHtml = (s: string): string =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

function buildHtml(cards: Array<{ name: string; description: string; tags: string[]; svg: string }>): string {
  const sections = cards
    .map(
      (c) => `
    <figure class="card" id="${c.name}">
      <figcaption>
        <h2>${escapeHtml(c.name)}</h2>
        <p>${escapeHtml(c.description)}</p>
        <small>${c.tags.map((t) => `<span class="tag">${escapeHtml(t)}</span>`).join(' ')}</small>
      </figcaption>
      <div class="stage">${c.svg}</div>
    </figure>`
    )
    .join('\n');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>RiffScore visual fixtures (#252)</title>
<style>
  @font-face { font-family: 'Bravura'; src: url('Bravura.woff2') format('woff2'); font-display: block; }
  :root { color-scheme: light dark; }
  body { font: 14px/1.5 system-ui, sans-serif; margin: 0; padding: 24px; background: #fafafa; color: #111; }
  h1 { font-size: 20px; }
  .meta { color: #666; margin-bottom: 24px; }
  .card { margin: 0 0 28px; padding: 16px; background: #fff; border: 1px solid #e3e3e3; border-radius: 10px; }
  figcaption h2 { margin: 0; font-size: 15px; font-family: ui-monospace, monospace; }
  figcaption p { margin: 4px 0 8px; color: #444; }
  .tag { font-size: 11px; background: #eef; color: #335; padding: 1px 6px; border-radius: 999px; }
  .stage { overflow-x: auto; padding: 8px 0; }
  /* The canvas SVG glyphs are SMuFL codepoints — render them with the music font. */
  .stage svg text { font-family: 'Bravura', serif; }
  @media (prefers-color-scheme: dark) {
    body { background: #16181c; color: #e8e8e8; }
    .card { background: #1f2228; border-color: #2c2f36; }
    figcaption p { color: #b9bcc2; }
  }
</style>
</head>
<body>
  <h1>RiffScore visual fixtures</h1>
  <p class="meta">${cards.length} fixtures · generated by <code>npm run visual:gallery</code> · issue #252.
     This is a human eyeball check (Lane B's cheap step); the automated nets are Jest fact-snapshots (Lane A) and Playwright pixel-diff (Lane B).</p>
  ${sections}
</body>
</html>`;
}

describe('visual gallery generator', () => {
  (ENABLED ? it : it.skip)('writes ./visual-gallery/index.html (set VISUAL_GALLERY=1)', () => {
    fs.mkdirSync(OUT_DIR, { recursive: true });

    const cards = visualFixtures.map((f) => {
      const { svg, unmount } = renderScore(f.score);
      unmount();
      return { name: f.name, description: f.description, tags: f.tags, svg };
    });

    fs.writeFileSync(path.join(OUT_DIR, 'index.html'), buildHtml(cards), 'utf8');
    if (fs.existsSync(FONT_SRC)) {
      fs.copyFileSync(FONT_SRC, path.join(OUT_DIR, 'Bravura.woff2'));
    }

    expect(fs.existsSync(path.join(OUT_DIR, 'index.html'))).toBe(true);
    console.log(`\n  Visual gallery written: ${path.join(OUT_DIR, 'index.html')}\n`);
  });
});
